- hosts: localhost
  connection: local
  gather_facts: true
  become: yes
  include_role:
    name: Ansible-RHEL7-CIS-Benchmarks
    tasks_from: "{{ hostvar }}.yml"
 
#  roles:
#    - Ansible-RHEL7-CIS-Benchmarks 
#  tasks:
#    - include_tasks: "{{ item }}"
#       with_fileglob: 
    
    
    
#    - include: "{{ item }}"
#  with_fileglob:
#    - roles/Ansible-RHEL7-CIS-Benchmarks/tasks/ path/to/your/tasks/*.yml
