      
---
- hosts: localhost
  connection: local
#  gather_facts: true
  #become: yes
  user: root
  tasks: 
    - name: make inventory
      add_host:
       name: '10.5.32.204'
      ansible_host: '10.5.32.203'
      ansible_become: true
      ansible_user: root

- hosts:  '10.5.32.204'
  become: true
  vars:
    - ansible_ssh_user: rotero1 
    - ansible_ssh_pass: rotero1.1
    - cis_target_os_distribution: "RedHat"
    - cis_apply_level_1_profile: false
    - cis_apply_level_2_profile: true
    - cis_level_2_exclusions:
      - 4.1.2
      
#  vars:
#    cis_target_os_distribution: "RedHat"
#    cis_apply_level_1_profile: false    # Whether Level 1 of the benchmark should be applied
#    cis_apply_level_2_profile: true    # Whether Level 2 of the benchmark should be applied
#    cis_level_2_exclusions:
#      - 4.1.2
     # - '4.1'
 

  #vars:
  #  cis_level_1_exclusions:
  #    - 5.4.4
  #    - 3.4.2
  #    - 3.4.3
  #    - 6.2.13   
  #  cis_pass_max_days: 45
  #  cis_umask_default: 002
    
  roles:
    - Ansible-RHEL7-CIS-Benchmarks 
