      
---
- hosts: 10.5.32.204 #localhost
  connection: local
  gather_facts: true
  become: yes

      
  vars:
    cis_target_os_distribution: "RedHat"
    cis_apply_level_1_profile: true    # Whether Level 1 of the benchmark should be applied
    cis_apply_level_2_profile: false    # Whether Level 2 of the benchmark should be applied
    cis_level_1_exclusions:
       - 1.1.1.1
       - 1.3.1
       - 1.3.2 
       - 1.5.1
       - 1.5.3
       - 1.7.1.2 # Banner
       - 1.7.1.3 # Banner
       - 2.1.11  #Deamon Extended Internet Service
       - 2.1.12 
       - 2.2.13 #Proxy Squid
       - 2.2.12
       - 2.1.1
       - 2.1.2 # Ensure daytime services are not enabled
       - 2.1.3 # Ensure discard services are not enabled
       - 2.1.4 # Ensure echo services are not enabled
       - 2.1.5 # Ensure time services are not enabled
       - 2.1.6 # Ensure rsh server
       - 2.1.7 # Ensure talkd server
       - 2.1.8 # Ensure telnet server
       - 2.1.9 # Ensure tftp server
       - 2.1.10 # Ensure rsync server
       - 2.2.1.1 # Ensure ntp is installed
       - 2.2.1.2 # Install NTP configuration
       - 2.2.1.3 # Install chrony configuration
       - 2.2.12 # Ensure SMB service
       - 2.2.2 # Ensure X Window System
       - 2.2.3 # Ensure Avahi Server is not enabled
     # - 4.1.2
     # - '4.1'
 

  #vars:
  #  cis_level_1_exclusions:
  #    - 5.4.4
  #    - 3.4.2
  #    - 3.4.3
  #    - 6.2.13   
  #  cis_pass_max_days: 45
  #  cis_umask_default: 002
    
  roles:
    - Ansible-RHEL7-CIS-Benchmarks 
