      
---
- hosts: 10.5.32.204 #localhost
  connection: local
  gather_facts: true
  become: yes

      
  vars:
    cis_target_os_distribution: "RedHat"
    cis_apply_level_1_profile: true    # Whether Level 1 of the benchmark should be applied
    cis_apply_level_2_profile: false    # Whether Level 2 of the benchmark should be applied
    cis_level_1_exclusions:
       - 1.1.1.1
       - 1.3.1
       - 1.3.2 
       - 1.5.1
       - 1.5.3
       - 1.7.1.2 # Banner
       - 1.7.1.3 # Banner
       - 2.1.11  #Deamon Extended Internet Service
       - 2.1.12 
       - 2.2.13 #Proxy Squid
       - 2.2.12
       - 2.1.1
       - 2.1.2 # Ensure daytime services are not enabled
       - 2.1.3 # Ensure discard services are not enabled
       - 2.1.4 # Ensure echo services are not enabled
       - 2.1.5 # Ensure time services are not enabled
       - 2.1.6 # Ensure rsh server
       - 2.1.7 # Ensure talkd server
       - 2.1.8 # Ensure telnet server
       - 2.1.9 # Ensure tftp server
       - 2.1.10 # Ensure rsync server
       - 2.2.1.1 # Ensure ntp is installed
       - 2.2.1.2 # Install NTP configuration
       - 2.2.1.3 # Install chrony configuration
       - 2.2.12 # Ensure SMB service
       - 2.2.2 # Ensure X Window System
       - 2.2.3 # Ensure Avahi Server is not enabled
       - 2.2.4 # Ensure CUPS is not enabled
       - 2.2.5 # Ensure DHCP Server is not enabled
       - 2.2.6 # Ensure LDAP server is not enabled
       - 2.2.7 # Ensure NFS and RPC Bind services is not enabled
       - 2.2.8 # Ensure DNS Bind/Named services are correct
       - 2.2.9 # Ensure FTP services are correct
       - 2.2.10 # Ensure HTTP services is not enabled
       - 2.2.11 # Ensure POP3 and IMAP services is not enabled
       - 2.2.12
       - 2.2.13
       - 2.2.14
       - 2.2.15
       - 2.2.16
       - 3.1.1 # Ensure IP forwarding is disabled
       - 3.1.2
       - 3.2.1
       - 3.2.2
       - 3.2.3
       - 3.2.4
       - 3.2.5
       - 3.2.6
       - 3.2.7
       - 3.2.8 # Ensure TCP SYN Cookies is enabled
       - 3.3.1 # Ensure IPv6 router advertisements are not accepted
       - 3.3.2 # Ensure IPv6 redirects are not accepted
       - 3.3.3 # 3.3.3 - Ensure IPv6 is disabled
       - 3.4.1 # 3.4.1 Ensure TCP Wrappers is installed - check
       - 3.4.2 # 3.4.2 - Ensure /etc/hosts.allow
       - 3.4.3 # 3.4.3 Ensure /etc/hosts.deny is configured
       - 3.4.4 # 3.4.4 - Ensure permissions on /etc/hosts.allow are configured
       - 3.4.5 # 3.4.5 - Ensure permissions on /etc/hosts.deny are configured
       - 3.6.1 # 3.6.1 - Ensure firewalld is install
       - 4.2.3 # 4.2.3 - Ensure rsyslog is installed
       - 4.2.1.1 # 4.2.1.1 - Check if rsyslog is installed
       - 4.2.1.3 # 4.2.1.3 - Ensure rsyslog default file permissions configured
       - 4.2.1.4 # 4.2.1.4 - Ensure rsyslog is configured to send logs to a remote log host
       - 4.2.1.5 # Ensure remote rsyslog messages are only accepted on designated log hosts
       - 4.2.2.1 # Check if syslog-ng is installed
       - 4.3 # 4.3 Ensure logrotate is configured
 

  #vars:
  #  cis_level_1_exclusions:
  #    - 5.4.4
  #  cis_pass_max_days: 45
  #  cis_umask_default: 002
    
  roles:
    - Ansible-RHEL7-CIS-Benchmarks 
