---

- hosts: 10.5.32.203
  connection: local
  gather_facts: true
  become: yes
  user: rotero1
  
  vars:
    cis_level_1_exclusions:
      - 5.4.4
      - 3.4.2
      - 3.4.3
      - 6.2.13   
    cis_pass_max_days: 45
    cis_umask_default: 002
    
  roles:
    - Ansible-RHEL7-CIS-Benchmarks 
